
---
sagify:

  train:
    input_s3_dir: s3://qa-kenza/iris.data
    output_s3_dir: s3://qa-kenza/pavlos/models
    ec2_type: ml.m5.large
    #hyperparameters_file: hyperparameters.json
    volume_size: 10
    timeout: 86400
    #metrics: Accuracy
    
    deploy:
      instances_count: 1
      ec2_type: ml.t2.medium
      endpoint: joakim-endpoint-test-import-sagify
